version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam5"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1i43oxfc41m4u"
s3_prefix = "sam5"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
